server:
  port: 8080
  servlet:
    context-path: /gc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qzs
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #druid线程池
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 2 #初始化大小
      max-active: 20 #最大值
      max-wait: 60000 #连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #间隔多久才进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000 #一个连接在池中最小生存的时间
      stat-view-servlet: #管理页面
        enabled: true
        url-pattern: /druid/*
#开启驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
